blank_issues_enabled: false
contact_links:
  - name: Project Nebula Website
    url: https://about.utdnebula.com
    about: Go here to learn more about Project Nebula's products.
  - name: Website Development Questions
    url: https://github.com/UTDNebula/website/discussions
    about: Have a general thought for the website? Discuss it here.
  - name: Report a security vulnerability
    url: security@utdnebula.com
    about: Please report security vulnerabilities here.
